### ISSUE TITLE
Add 2 cooks and movement in-game

### ISSUE THREAD

**Issue by hs1955** [undercooked-team/UnderCooked#19]
Add 2 cooks into the game code, along with a way for the player to move each cook.

**Comment by OwenTho** [comment]
This was implemented 2023/01/25 within the commit [fbe1e84ff03087366701692fbfd8d027616e5350](https://github.com/undercooked-team/UnderCooked/commit/fbe1e84ff03087366701692fbfd8d027616e5350#diff-3714281400e5ad914639e3d6a8159dcb7e7c34d68db610b1b80085e03ae5f84d).
