### ISSUE TITLE
Add Timers

### ISSUE THREAD

**Issue by hs1955** [undercooked-team/UnderCooked#20]
Add the code to make the player have to serve 5 customers. The game is won after each of the 5 customers has been served.

**Comment by OwenTho** [comment]
Timer was added to Hud on 2023/01/25 in the commit [c491995aeda6d295fdd6d6c10f6fba25790201c7](https://github.com/undercooked-team/UnderCooked/commit/c491995aeda6d295fdd6d6c10f6fba25790201c7), and the timer function was first implemented on 2023/01/26 in the commit [3483d1d7b26ad91860806f990cc26a19605130bf](https://github.com/undercooked-team/UnderCooked/commit/3483d1d7b26ad91860806f990cc26a19605130bf).

**Comment by hs1955** [comment]
Changed the title of this task, as this task was far too broad, and is now broken down into several smaller tasks.

Timer has successfully been added.
