### ISSUE TITLE
Create UnderCooked Architecture

### ISSUE THREAD

**Issue by hs1955** [undercooked-team/UnderCooked#4]
This will most likely involve class diagrams.

**Comment by fridgefin** [comment]
worked on architecture deliverable 9/12/2022

**Comment by fridgefin** [comment]
- added image of the merged RDD idea board
- added image of UML class diagram based on RDD idea board
- wrote a bit about the class diagram

**Comment by hs1955** [comment]
This task has been completed. See our architecture info on the website.
