### ISSUE TITLE
Create UnderCooked Risk Assessment

### ISSUE THREAD

**Issue by hs1955** [undercooked-team/UnderCooked#5]

**Comment by OwenTho** [comment]
Wrote about the Identificaton Process for Risk Management, and added a few examples of risks.
Ideally, we should work on this more in the next meeting we have.

First, as the Identification Process may need slight altering from how the team as a whole believes we should conduct the process. For example, it is recommended to share any new risks or alterations made to existing ones have been made once or twice a month so everyone is up to date.

Secondly, as we have to allocate an "Owner" for every risk who will oversee the risk and alter the likelihood and severity, possibly even the avoidance strategy, mitigation strategy or contingency plan, and provide reports on any changes during the recommended meeting. This would be better done as a group when we have planned out what aspect of the system each team member will be allocated towards.

**Comment by SamDavis01** [comment]
Added some other risks along with their likelihood, severity and mitigation to the risk management.

**Comment by hs1955** [comment]
This task has been finished, check out our Risk Assessment on the website.
