### ISSUE TITLE
Create Method Selection and Planning

### ISSUE THREAD

**Issue by hs1955** [undercooked-team/UnderCooked#9]

**Comment by OwenTho** [comment]
Compiled a list of points to include in the document with @fridgefin, @SamDavis01

**Comment by OwenTho** [comment]
Finished the first section, the Outline of our Method Selection and Planning, of this deliverable.

**Comment by OwenTho** [comment]
Worked on the second section, the Team Organisation, of this deliverable.

**Comment by OwenTho** [comment]
Worked on the third section, the Project Plan, of this deliverable.

**Comment by hs1955** [comment]
This deliverable has been completed. See the Method Selection and Planning doc on the website.
